/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:11f3ba33-5d4e-44d2-89dd-efc091784a72",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_smrvYHWPC",
    "aws_user_pools_web_client_id": "4vr9siuucgpq2ldtoan2nbtg7e",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://qevmpd5bhrf47dgxwvv4iqudjq.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zbucoo6ygrb65ekcuuru2vsiui",
    "aws_user_files_s3_bucket": "awsdemo1231547-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
